### PR TITLE
polished readme

### PR DESCRIPTION
**Pull request by vonovak**

### CODE REVIEW

**Comment by vonovak** [comment]
@mweststrate should be good to go. I mostly corrected small typos and replaced `ref` with `reference` and `child` with `object`. Also added an example for list of primitives.

**Comment by mweststrate** [comment]
thanks big time for your effort! note that the api section is generated directly from the source file.  would you mind updating that one? otherwise changes will be partially lost in the next release

**Comment by vonovak** [comment]
Oh, right, I should've noticed that. I'll take a look at it.

**Comment by vonovak** [comment]
closing in favor of #16

**Pull request closed without merging**
