### PR TITLE
Support prop schemas for "*" properties

### PR DESCRIPTION
**Pull request by pyrogenic**
## Issue

"*" properties only allow primitive values, but there are numerous use cases where complex objects are the values of a dictionary.

## Solution

Allow "*" to have a `PropSchema` value.

## Dependancies

- [x] #99 Allow serializing plain objects by specifying constructor
- [x] #104 Support optional properties

### CODE REVIEW

**Comment by mweststrate** [comment]
Hi @pyrogenic! Superficially speaking changes look good to me! However, I havent worked on this code base for the past 2 or 3 years. If you want, I can make you a maintainer of this repo, and add npm publish permissions as well, enabling you to release once you feel comfortable about it. 

I did note that the yarn.lock file has been removed. Are you using npm? Would you mind running yarn to make sure the lock file is preserved?

Thanks!

**Comment by pyrogenic** [comment]
Hi Michael,

I'd be happy to help maintain the repo — we're already using my fork
(published as @pyrogenic/serializr) in production code.

Would you want to continue reviewing PRs, or would you rather I enlist
colleagues of mine?

I'll check into the lockfile — at one point I thought I'd added it in error.

Cheers,
-josh.

**Comment by mweststrate** [comment]
awesome, feel free to add your colleagues! I think things are best reviewed by people currently using it, which doesn't include me at the moment :)

**Comment by pyrogenic** [comment]
@mweststrate restored lockfile 8cf098b

**Pull request merged**
