### PR TITLE
update documentation for usage of optional with custom

### PR DESCRIPTION
**Pull request by blacksteed232**
See discussion in #128

### CODE REVIEW

**Comment by NaridaL** [comment]
Does `optional(custom())` make sense at all? 

In any case, I think your example calls `value => value.name` with value `undefined`, which results in an error.

**Comment by blacksteed232** [comment]
> Does `optional(custom())` make sense at all?
> 
> In any case, I think your example calls `value => value.name` with value `undefined`, which results in an error.
> 
> Maybe it makes more sense to write that if you're using custom, you don't need optional.
> 
> `custom(v => v.?name ?? SKIP, v => {})`

@NaridaL yes! that's definitely my use case, and so I thought I could use `optional` to be more declarative. For example:

```javascript
const todoSchema = createSimpleSchema({
  name: optional(custom(..)) // more declarative than 'custom( ... return SKIP ...)
})
```
Then I tried `optional(custom())` and found out did not work quite the way I expected.

@pyrogenic thanks!

**Comment by NaridaL** [comment]
image

image

**Comment by blacksteed232** [comment]
@NaridaL I have corrected the example in #132

**Pull request merged**
