### PR TITLE
Prettify js within readme, fix typos

### PR DESCRIPTION
**Pull request by brikou**
I found typos in JS in readme so I fixed those and also prettify everything to have a consistent coding style.

Thank you for you hard work @mweststrate  with this lib :+1:

### CODE REVIEW

**Comment by mweststrate** [comment]
Note that the examples for specific api methods are generated from source, so should be updated in the `@example` sections in the source code

**Comment by brikou** [comment]
Done

**Comment by brikou** [comment]
@mweststrate is this fine for you ?

**Comment by mweststrate** [comment]
Perfect! Thanks a lot

**Pull request merged**
